# GUIDELINES FOR ORGANIC CHICKEN PRODUCTION IN MALAYSIA

## 1.0 OBJECTIVE
This guideline provides information on basic requirements for organic chicken farming in Malaysia.

## 2.0 SCOPE
This guideline covers important aspects in the production of organic broiler chicken from the origin until slaughtering including record keeping.

## 3.0 REFERENCE
3.1 Animals Act 1953 (Revised 2006); 
3.2 Arahan Prosedur Tetap Veterinar Malaysia : Penghapusan, 2010;
3.3 Feed Act 2009; 
3.4 Malaysian Organic Scheme (SOM) - Department of Agriculture Malaysia;
3.5 Organically Produced Foods, Third Edition, 2007 - Codex Alimentarius Commission;
3.6 Organic Poultry Production In The United States, 2008 - www.attra,ncat.org 
3.7 Organic Production Systems General Principles and Management Standards, 2006, Canadian General Standards Board, http://www.tpsgc-pwgsc.gc.ca;
3.8 Organic Poultry Farming, 2012 - http://www.ecocert.com
3.9 Philippine National Standard Specification for Organic Agriculture, Bureau of Product Standards, Department of Trade and Industry, Philippines, 2003; 
3.10 The IFOAM Standard for Organic Production and Processing.

## 4.0 DEFINITION

### 4.1 Additive 
An enrichment, supplement or other substance which can be added to a foodstuff or other product to affect its keeping quality, consistency, color, taste, smell or other technical property.

### 4.2 Alternative 
medicine A variety of therapeutic or preventive health care practices, such as Ayurveda, homeopathy, naturopathy and herbal medicine, that do not follow generally accepted medical methods and may not have a scientific explanation for their effectiveness. The use of surgery and drugs are minimized or totally avoided in the practice.

### 4.3 Conversion period 
The time between the start of the organic management and the acceptance of crops and animal husbandry as organic. Conventional Any material, production or processing practice that is not organic or organic 'in conversion'.

### 4.5 Genetic Modified Organism (GMO) 
A set of techniques from molecular biology (such as
recombinant DNA) by which the genetic material of plants, animals, micro-organisms, cells and other biological units are altered in ways or with results that could not be obtained by methods of natural mating and reproduction or natural recombination. Genetically engineered organisms do not include organisms resulting from techniques such as conjugation, transduction and natural hybridization.

### 4.6 Organic 
Labelling term that denotes products that have been produced in accordance with organic production standards and certified by a duly constituted certification body or
authority.

### 4.7 Organic chicken 
Chicken that are raised and handled in compliance with organic standard.

### 4.8 Veterinary authority 
The Director General of Veterinary Services, the Deputy Director General of Veterinary Services and any State Director of Veterinary Services, any Veterinary Officer, Deputy or Assistant Veterinary Officer and includes any person appointed in writing by the Director General of Veterinary Services, the Deputy Director General of Veterinary Services and any State Director of Veterinary Services, to be a veterinary authority under section 3 of Animals Act, 1953 (Revised 2006).

## 5.0 ABBREVIATION
### 5.1 DVS - Department of Veterinary Services Malaysia

## 6.0 GUIDELINES
### 6.1 Origin and Choice of Breed
6.1.1 The origin of the chicken is preferably from organic sources. 
6.1.2 When organic chicken is not available, non-organic day-old chicks may be brought in. 
6.1.3 The choice of breeds shall take into consideration them following criteria: 
6.1.3.1 Their adaptation to the local conditions;
6.1.3.2 Their vitality and resistance to disease; 
6.1.3.3 The absence of specific diseases or health problems associated with some breeds and strains.

### 6.2 Conversion Period
6.2.1 Non-organic chicks must undergo organic management for the whole life span from day-old onwards.



used are suitable for raising under local conditions and under an organic system. 

6.4.3 Operation such as trimming of beaks is generally not allowed in the organic management system. 
6.4.4 The living conditions and the management of the environment shall take into account the specific behavioral needs of the chicken and provide for: 
6.4.4.1 Sufficient free movement and opportunity to express normal patterns of behaviour; 
6.4.4.2 Company of other chicken; 
6.4.4.3 The prevention of abnormal behaviour, injury and disease; 
6.4.4.4 Arrangements to cover emergencies such as the outbreaks of fire, the breakdown of essential mechanical services and the disruption of supplies.

### 6.5 Nutrition
6.5.1 Feed ration must provide the level of nutrients (protein, energy, minerals and vitamins) appropriate at various stages of its development. 
6.5.2 The feed must be organic, including pasture and forage. 
6.5.3 Processed feed must be from a government approved organic feed mill. 
6.5.4 Organic chicken must have ample access to fresh water to maintain its full health and vigour.
6.5.5 Substances used as feedstuffs, nutritional elements, feed additives or processing aids in the preparation of feedstuffs shall comply with the following criteria: 
6.5.5.1 Necessary/essential to maintain animal health, animal welfare and vitality; 
6.5.5.2 Contribute to an appropriate diet fulfilling the physiological and behavioural needs of the
species concerned; 
6.5.5.3 Do not contain genetically engineered /modified organisms and products thereof; 
6.5.5.4 Are primarily of plant, mineral or animal origin from organic source. 
6.5.5.5 Feedstuffs of mineral origin, trace elements, vitamins, or provitamins can only be used if they are of natural origin. 
6.5.5.6 Synthetic nitrogen or non-protein nitrogen compounds shall not be used. 

6.5.6 Specific criteria for additives and processing aids: 
6.5.6.1 Only natural sources are allowed:
a. Binders, anti-caking agents, emulsifiers, stabilizers, thickeners, surfactants, coagulants; 
b. Anti-oxidants; 
c. Preservatives; 
d. Colouring agents (including pigments), flavours; and
e. Appetite stimulant. 

6.5.6.2 Allowed:
a. Probiotics;
b. Enzymes; and 
c. Micro-organisms. 

6.5.6.3 Shall not be used in animal feeding
a. Antibiotics; 
b. Coccidiostatics; and 
c. Medicinal substances, growth promoters or any other substance intended to stimulate growth or production.

### 6.6 Health Management

6.6.1 Disease prevention in organic chicken production shall be based on the following principles:

6.6.1.1 The choice of appropriate breeds of chicken (as in 6.1.3); 
6.6.1.2 The application of required animal husbandry practices, encourages strong resistance to
disease and the prevention of infections; 
6.6.1.3 The use of good quality feed, together with regular exercise and access to pasture and/or open-air runs, also encourage the natural immunological defense of the animal; 
6.6.1.4 Ensuring an appropriate density of livestock, thus avoiding overstocking and any resulting
animal health problems. 

6.6.2 Operators shall give preference to natural medicines and treatments, or other alternative medicines to treat sick or injured chicken.

6.6.3 If the use of above product is unlikely to be effective, chemical allopathic veterinary drug or antibiotic may be used under veterinary supervision. 

6.6.4 Use of chemical allopathic veterinary drugs or antibiotics will cause the chicken to lose its organic status. Producers shall not withhold such medication where it will result in unnecessary suffering of the chicken. 

6.6.5 Withdrawal periods of chemical allopathic veterinary drugs shall be double of that required by manufacturer; 

6.6.6 Vaccinations are allowed only in the following cases:
a. when an endemic disease is known or expected to be a problem in the region of the farm and where this disease cannot be controlled by other management techniques, or
b. when a vaccination is legally required. 

6.6.7 The use of chemical allopathic veterinary drugs or antibiotics for preventive treatments is not permitted.


### 6.7 Slaughter
6.7.1 Slaughtering premises shall be registered with local authority. 
6.7.2 Chicken shall be determined healthy by veterinary authority before slaughtering. 
6.7.3 Slaughtering shall be undertaken in a manner which minimizes stress and suffering.

### 6.8 Storage
6.8.1 Product integrity shall be maintained during any storage and handling by use of the following precautions: 
6.8.1.1 Organic products must be protected at all times from co-mingling with non-organic
products; and 
6.8.1.2 Organic products must be protected at all times from contact with materials and substances not permitted for use in organic farming and handling. 

6.8.2 Where only part of the unit is certified, other product not covered by these guidelines shall be stored and handled separately and both types of products shall be clearly identified. 
6.8.3 Bulk stores for organic product shall be separate from conventional product stores and clearly labelled to that effect. 
6.8.4 Storage areas and containers for organic product shall be cleaned using methods and materials permitted in organic production. Measures shall be taken to prevent possible contamination from any pesticide or other treatment not listed in Annex before using a storage area or container that is not dedicated solely to organic products.

### 6.9 Transportation
6.9.1 The transport of chicken shall be managed in a calm and gentle way and in a manner which avoids stress, injury and suffering; 
6.9.2 The chicken shall have suitable shelter against inclement weather conditions (e.g. wind, rain, excessive heat) during transport; 
6.9.3 The chicken shall be transported directly from the farm to their final destination; 
6.9.4 The duration of transport shall be as short as possible; 
6.9.5 In transporting livestock, the use of electric stimulation or allopathic tranquilizers is not permitted.

### 6.10 Waste Management
6.10.1 Farm waste including dead chicken shall be properly disposed to prevent contamination and disturbances of environment and transmission of diseases. 
6.10.2 Disposal procedure shall not include burning or any practice inconsistent with organic practices. 6.10.3 Disposal area shall be separated from the rearing area and water sources.

### 6.11 Pest Management
6.11.1 For pest management and control the following measures, in order of preference, shall be used: 
6.11.1.1 Preventative methods, such as disruption and elimination of habitat and access to facilities by pest organisms, shall be the primary methodology of pest management; 

6.11.1.2 If preventative methods are inadequate, the first choice for pest control shall be
mechanical/physical and biological methods;
6.11.1.3 If mechanical/physical and biological methods are inadequate for pest control, pesticidal substances appearing in Annex may be used provided that contact with
organic products is prevented. 
6.11.2 Only pesticides listed in Annex shall be used for post harvest or quarantine purposes.

### 6.12 Record keeping
All chicken shall be identified by flock. Written and/or documentary accounts shall be kept to enable tracking of chicken within the system at all times and to provide adequate traceback for audit purpose. The operator shall maintain detailed and up-to-date records of: 
6.12.1 Breeding and/or origins of chicken ; 
6.12.2 Registration of any purchases; 
6.12.3 The health plan to be used in the prevention and management of disease and injury; 
6.12.4 All treatments and medicines administered for any purpose, including quarantine periods and identification of treated chicken; 
6.12.5 Feed provided and the source of the feedstuffs; 
6.12.6 Stock movements within the unit;
6.12.7 Transportation, slaughter and/or sales; 
6.12.8 Extraction, processing and storing of all chicken products.

For enquiries, please contact:
Diagnostic and Quality Assurance Division Department of Veterinary Services Level 2, Podium Block 4G1 Wisma Tani, Precinct 4
Federal Government Administrative Centre
62630 PUTRAJAYA Tel: 03-8870 2000 Fax: 03-8888 5755 Official portal : www.dvs.gov.my
ORGANIC CHICKEN PRODUCTION
