# Incubation and Hatching

## Location
Hatcheries ought to be located in areas with good infrastructure for easy accessibility. This will include transport, electricity, water and waste disposal systems. An ideal hatchery site should be located away from poultry production farms to prevent horizontal transmission of diseases from the chicken houses to the hatchery.

## Design

The movement of chicks and persons should be in one direction inside the hatchery. Design separate rooms
for receiving eggs, fumigating, setting, hatching and chick harvesting. To maintain bio-security it is important that all persons entering the hatchery shower and change into clean clothes in an adjoining room. The changing rooms should be the only entrance and exit that ensures the hatchery is an isolated unit. As such shower rooms, washing facilities, storage rooms and of?ces should be separated.

## Egg handling and storage
Once an egg is laid, its hatching potential can at best be maintained but not improved. When mishandled, the hatching potential quickly deteriorates. Select hatching eggs from a mature healthy flock where the males and females are not directly related. Avoid excessively large or small, cracked, dirty or those with thin shells and misshapen eggs. Optimum hatchability and Chick quality can only be achieved when the egg is held under optimum conditions between laying and setting in the incubator. Remember that a fertile egg contains many living cells.
Store the eggs with the sharp end down in a room where the temperature and humidity are controlled or at best maintained. Keep the egg handling room clean, tidy and maintain good vermin control.

## Incubation
Incubation involves four major functions. These are:
1. Temperatu re
2. Humidity
3. Ventilation
4. Egg position
5. Turning   

Fig. 79: Setter tray with eggs

## Temperature
The ideal temperature for incubation is 375°C or 99.50F. Overheating (above 400C) will harm the growing embryo while under heating (below 32°C) will slow down the chicks’ metabolic rate and consequently growth. Always remember that it takes time to warm up the eggs once placed in an incubator. Do not adjust the temperature set points before the time has lapsed.

## Humidity
The relative humidity for the ?rst 18 days should be 60 %. Less moisture will result in excessive evaporation causing chicks to stick to the shell at hatching. Too much moisture prevents normal evaporation and results in a decreased hatch. On the day 19-21 gradually increase the humidity to between 70-75%. This will prevent the beak from sticking to the shell. Use a wet bulb thermometer or hygrometer to determine the humidity.

## Ventilation
This is the air movement within the incubator and air exchange with air outside the incubator. As the embryo grows, it takes up oxygen and releases carbon dioxide through the pores in the eggshell. It is important to avoid the build up of carbon dioxide. This is controlled through the vents at the top or sides 0fthe incubator.

## Egg position
Eggs should be placed sharp end down during incubation. The growing embryo will naturally position its head near the air cell. When eggs are incubated with the sharp end up, chicks are unable to break the air cell during hatching. Under normally incubation eggs are set with the sharp end down for the first 18 days (in the setter) and in a horizontal position for the last 3—4 days in a hatcher.   


## Egg Turning
Eggs should be turned at least 8 times a day during incubation. In large automated incubators eggs are turned automatically once every hour, Le. 24 times daily. Most eggs are turned to a position of 45° from the vertical position. This prevents the embryo from sticking to the shell membranes, particularly during the ?rst week of incubation, and aids development of embryonic membranes. As embryos develop and their heat production increases, regular turning will aid airflow and assist cooling. 

## Hatching processes   






