# Introduction

Chicken are the most abundant livestock in many rural and peri—urban households in Kenya. These chickens are also referred to as rural, village, baclward, scavenging, traditional or family chickens, and have various names in local languages. They play an importantrole in household economies in that they convert feed resources available in the household into highly nutritious and valuable protein products. Although their output in terms of weight gain and number of eggs per hen per year is low, it is obtained with minimal labour and other inputs. The low input and, consequently, low risk is one ofthe major advantages of extensive indigenous chicken production systems. Significant returns can be achieved from chicken without the need for expensive housing, complex technology and funding just by utilizing locally available resources.
Animal protein consumed in rural areas frequently comes from indigenous chicken meat and eggs. Chicken can also be sold or bartered to meet family needs such as medicines, clothes and school fees. In this way, they act as a ready source of cash for emergencies and small purchases. They also provide manure and play a role in pest control. These birds are also important during special festivals, traditional ceremonies and treatments.
Chicken meat and eggs provide a readily  available, high-quality source of proteins, vitamins and micronutrients. Eggs are an excellent source of iron, zinc and vitamin A, all of which are essential to health, growth and wellbeing. The products contribute to a nutritious, balanced diet, which is especially important for children, nursing mothers and vulnerable groups.
Population growth, rising incomes, lifestyle changes and health awareness has led to increased demand for poultry products. This calls for commercialization of the chicken industry to meet the increasing demand.     





